### ISSUE TITLE
Add a flumeview index

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-tribes#11]
Current stream code doesn't cover edge-cases where the server is stopped and started and may miss messages. Flumeviews solve this problem. :tada:

**Comment by mixmix** [comment]
I've looked into this, have tried an index to watch for `group/add-member`, actually decided to use a live existing index, because this way we can wait till we're up to sync before triggering a new re-index. This is useful because we don't want to hit the rebuild button multiple times if we hit 5 `group/add-member` in a row ... we only really want to re-index once for a particular group
